import type { ComponentType } from "react"

import {
  ContactSectionDemo,
  HeroSectionDemo,
  ModeToggleDemo,
  SiteHeaderDemo,
  SkillsSectionDemo,
  WorkSectionDemo,
} from "@/components/design-system/demos/custom-demos"
import { AiElementsDemo } from "@/components/design-system/demos/ai-elements-demo"
import { M3ShapesDemo } from "@/components/design-system/demos/m3-shapes-demo"
import { ScrollbarDemo } from "@/components/design-system/demos/scrollbar-demo"
import { PlaceholderDemo } from "@/components/design-system/demos/placeholder-demo"
import {
  AlertDemo,
  AvatarDemo,
  BadgeDemo,
  ButtonDemo,
  CardDemo,
  CheckboxDemo,
  DialogDemo,
  DropdownMenuDemo,
  InputDemo,
  SelectDemo,
  SeparatorDemo,
  SkeletonDemo,
  SwitchDemo,
  TabsDemo,
  TextareaDemo,
  TooltipDemo,
} from "@/components/design-system/demos/tier-1-demos"
import {
  AccordionDemo,
  AlertDialogDemo,
  AspectRatioDemo,
  BreadcrumbDemo,
  ButtonGroupDemo,
  CollapsibleDemo,
  DrawerDemo,
  EmptyDemo,
  FieldDemo,
  InputGroupDemo,
  KbdDemo,
  NativeSelectDemo,
  PaginationDemo,
  PopoverDemo,
  ProgressDemo,
  RadioGroupDemo,
  ResizableDemo,
  ScrollAreaDemo,
  SheetDemo,
  SliderDemo,
  SpinnerDemo,
  TableDemo,
  ToggleDemo,
  ToggleGroupDemo,
} from "@/components/design-system/demos/tier-2-demos"
import {
  CalendarDemo,
  LabelDemo,
  SonnerDemo,
} from "@/components/design-system/demos/tier-3-demos"
import {
  CarouselDemo,
  ChartDemo,
  ComboboxDemo,
  CommandDemo,
  ContextMenuDemo,
  HoverCardDemo,
  InputOtpDemo,
  ItemDemo,
  MenubarDemo,
  NavigationMenuDemo,
  SidebarDemo,
} from "@/components/design-system/demos/tier-4-demos"

export const componentDemos: Record<string, ComponentType> = {
  accordion: AccordionDemo,
  alert: AlertDemo,
  "alert-dialog": AlertDialogDemo,
  "aspect-ratio": AspectRatioDemo,
  avatar: AvatarDemo,
  badge: BadgeDemo,
  breadcrumb: BreadcrumbDemo,
  button: ButtonDemo,
  "button-group": ButtonGroupDemo,
  calendar: CalendarDemo,
  card: CardDemo,
  carousel: CarouselDemo,
  chart: ChartDemo,
  checkbox: CheckboxDemo,
  collapsible: CollapsibleDemo,
  combobox: ComboboxDemo,
  command: CommandDemo,
  "context-menu": ContextMenuDemo,
  dialog: DialogDemo,
  drawer: DrawerDemo,
  "dropdown-menu": DropdownMenuDemo,
  empty: EmptyDemo,
  field: FieldDemo,
  "hover-card": HoverCardDemo,
  input: InputDemo,
  "input-group": InputGroupDemo,
  "input-otp": InputOtpDemo,
  item: ItemDemo,
  kbd: KbdDemo,
  label: LabelDemo,
  menubar: MenubarDemo,
  "native-select": NativeSelectDemo,
  "navigation-menu": NavigationMenuDemo,
  pagination: PaginationDemo,
  popover: PopoverDemo,
  progress: ProgressDemo,
  "radio-group": RadioGroupDemo,
  resizable: ResizableDemo,
  "scroll-area": ScrollAreaDemo,
  select: SelectDemo,
  separator: SeparatorDemo,
  sheet: SheetDemo,
  sidebar: SidebarDemo,
  skeleton: SkeletonDemo,
  slider: SliderDemo,
  sonner: SonnerDemo,
  spinner: SpinnerDemo,
  switch: SwitchDemo,
  table: TableDemo,
  tabs: TabsDemo,
  textarea: TextareaDemo,
  toggle: ToggleDemo,
  "toggle-group": ToggleGroupDemo,
  tooltip: TooltipDemo,
  "m3-shapes": M3ShapesDemo,
  scrollbars: ScrollbarDemo,
  "mode-toggle": ModeToggleDemo,
  "site-header": SiteHeaderDemo,
  "hero-section": HeroSectionDemo,
  "work-section": WorkSectionDemo,
  "skills-section": SkillsSectionDemo,
  "contact-section": ContactSectionDemo,
  "ai-elements": AiElementsDemo,
}

export function getDemo(slug: string): ComponentType {
  return componentDemos[slug] ?? (() => <PlaceholderDemo name={slug} />)
}
