/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DesignSystemRouteRouteImport } from './routes/design-system/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DesignSystemIndexRouteImport } from './routes/design-system/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsResumeRouteImport } from './routes/tools/resume'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DesignSystemTypographyRouteImport } from './routes/design-system/typography'
import { Route as DesignSystemScrollbarsRouteImport } from './routes/design-system/scrollbars'
import { Route as DesignSystemColorsRouteImport } from './routes/design-system/colors'
import { Route as DesignSystemAccessibilityRouteImport } from './routes/design-system/accessibility'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DesignSystemComponentsSlugRouteImport } from './routes/design-system/components/$slug'
import { Route as ApiResumeUnlockRouteImport } from './routes/api/resume/unlock'
import { Route as ApiResumeSessionRouteImport } from './routes/api/resume/session'
import { Route as ApiResumeGenerateRouteImport } from './routes/api/resume/generate'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRouteRoute = DesignSystemRouteRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIndexRoute = DesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResumeRoute = ToolsResumeRouteImport.update({
  id: '/tools/resume',
  path: '/tools/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemTypographyRoute = DesignSystemTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemScrollbarsRoute = DesignSystemScrollbarsRouteImport.update({
  id: '/scrollbars',
  path: '/scrollbars',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemColorsRoute = DesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemAccessibilityRoute =
  DesignSystemAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemComponentsSlugRoute =
  DesignSystemComponentsSlugRouteImport.update({
    id: '/components/$slug',
    path: '/components/$slug',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const ApiResumeUnlockRoute = ApiResumeUnlockRouteImport.update({
  id: '/api/resume/unlock',
  path: '/api/resume/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeSessionRoute = ApiResumeSessionRouteImport.update({
  id: '/api/resume/session',
  path: '/api/resume/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeGenerateRoute = ApiResumeGenerateRouteImport.update({
  id: '/api/resume/generate',
  path: '/api/resume/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design-system/accessibility': typeof DesignSystemAccessibilityRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/scrollbars': typeof DesignSystemScrollbarsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/resume': typeof ToolsResumeRoute
  '/blog/': typeof BlogIndexRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/resume/generate': typeof ApiResumeGenerateRoute
  '/api/resume/session': typeof ApiResumeSessionRoute
  '/api/resume/unlock': typeof ApiResumeUnlockRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design-system/accessibility': typeof DesignSystemAccessibilityRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/scrollbars': typeof DesignSystemScrollbarsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/resume': typeof ToolsResumeRoute
  '/blog': typeof BlogIndexRoute
  '/design-system': typeof DesignSystemIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/resume/generate': typeof ApiResumeGenerateRoute
  '/api/resume/session': typeof ApiResumeSessionRoute
  '/api/resume/unlock': typeof ApiResumeUnlockRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design-system/accessibility': typeof DesignSystemAccessibilityRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/scrollbars': typeof DesignSystemScrollbarsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/resume': typeof ToolsResumeRoute
  '/blog/': typeof BlogIndexRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/resume/generate': typeof ApiResumeGenerateRoute
  '/api/resume/session': typeof ApiResumeSessionRoute
  '/api/resume/unlock': typeof ApiResumeUnlockRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/about'
    | '/resume'
    | '/api/chat'
    | '/blog/$slug'
    | '/design-system/accessibility'
    | '/design-system/colors'
    | '/design-system/scrollbars'
    | '/design-system/typography'
    | '/projects/$slug'
    | '/tools/resume'
    | '/blog/'
    | '/design-system/'
    | '/projects/'
    | '/api/resume/generate'
    | '/api/resume/session'
    | '/api/resume/unlock'
    | '/design-system/components/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/resume'
    | '/api/chat'
    | '/blog/$slug'
    | '/design-system/accessibility'
    | '/design-system/colors'
    | '/design-system/scrollbars'
    | '/design-system/typography'
    | '/projects/$slug'
    | '/tools/resume'
    | '/blog'
    | '/design-system'
    | '/projects'
    | '/api/resume/generate'
    | '/api/resume/session'
    | '/api/resume/unlock'
    | '/design-system/components/$slug'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/about'
    | '/resume'
    | '/api/chat'
    | '/blog/$slug'
    | '/design-system/accessibility'
    | '/design-system/colors'
    | '/design-system/scrollbars'
    | '/design-system/typography'
    | '/projects/$slug'
    | '/tools/resume'
    | '/blog/'
    | '/design-system/'
    | '/projects/'
    | '/api/resume/generate'
    | '/api/resume/session'
    | '/api/resume/unlock'
    | '/design-system/components/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRouteRoute: typeof DesignSystemRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ResumeRoute: typeof ResumeRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ToolsResumeRoute: typeof ToolsResumeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiResumeGenerateRoute: typeof ApiResumeGenerateRoute
  ApiResumeSessionRoute: typeof ApiResumeSessionRoute
  ApiResumeUnlockRoute: typeof ApiResumeUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/': {
      id: '/design-system/'
      path: '/'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemIndexRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/resume': {
      id: '/tools/resume'
      path: '/tools/resume'
      fullPath: '/tools/resume'
      preLoaderRoute: typeof ToolsResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/typography': {
      id: '/design-system/typography'
      path: '/typography'
      fullPath: '/design-system/typography'
      preLoaderRoute: typeof DesignSystemTypographyRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/scrollbars': {
      id: '/design-system/scrollbars'
      path: '/scrollbars'
      fullPath: '/design-system/scrollbars'
      preLoaderRoute: typeof DesignSystemScrollbarsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/colors': {
      id: '/design-system/colors'
      path: '/colors'
      fullPath: '/design-system/colors'
      preLoaderRoute: typeof DesignSystemColorsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/accessibility': {
      id: '/design-system/accessibility'
      path: '/accessibility'
      fullPath: '/design-system/accessibility'
      preLoaderRoute: typeof DesignSystemAccessibilityRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/components/$slug': {
      id: '/design-system/components/$slug'
      path: '/components/$slug'
      fullPath: '/design-system/components/$slug'
      preLoaderRoute: typeof DesignSystemComponentsSlugRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/api/resume/unlock': {
      id: '/api/resume/unlock'
      path: '/api/resume/unlock'
      fullPath: '/api/resume/unlock'
      preLoaderRoute: typeof ApiResumeUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume/session': {
      id: '/api/resume/session'
      path: '/api/resume/session'
      fullPath: '/api/resume/session'
      preLoaderRoute: typeof ApiResumeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume/generate': {
      id: '/api/resume/generate'
      path: '/api/resume/generate'
      fullPath: '/api/resume/generate'
      preLoaderRoute: typeof ApiResumeGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignSystemRouteRouteChildren {
  DesignSystemAccessibilityRoute: typeof DesignSystemAccessibilityRoute
  DesignSystemColorsRoute: typeof DesignSystemColorsRoute
  DesignSystemScrollbarsRoute: typeof DesignSystemScrollbarsRoute
  DesignSystemTypographyRoute: typeof DesignSystemTypographyRoute
  DesignSystemIndexRoute: typeof DesignSystemIndexRoute
  DesignSystemComponentsSlugRoute: typeof DesignSystemComponentsSlugRoute
}

const DesignSystemRouteRouteChildren: DesignSystemRouteRouteChildren = {
  DesignSystemAccessibilityRoute: DesignSystemAccessibilityRoute,
  DesignSystemColorsRoute: DesignSystemColorsRoute,
  DesignSystemScrollbarsRoute: DesignSystemScrollbarsRoute,
  DesignSystemTypographyRoute: DesignSystemTypographyRoute,
  DesignSystemIndexRoute: DesignSystemIndexRoute,
  DesignSystemComponentsSlugRoute: DesignSystemComponentsSlugRoute,
}

const DesignSystemRouteRouteWithChildren =
  DesignSystemRouteRoute._addFileChildren(DesignSystemRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRouteRoute: DesignSystemRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ResumeRoute: ResumeRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ToolsResumeRoute: ToolsResumeRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiResumeGenerateRoute: ApiResumeGenerateRoute,
  ApiResumeSessionRoute: ApiResumeSessionRoute,
  ApiResumeUnlockRoute: ApiResumeUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
